name: py.test

on:
  push:
    branches:
      - "**"
      - "!integration"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
      TWILIO_TEST_ACCOUNT_SID: "AC08ab400d1525a96b92030f15e0776f47"
      TWILIO_TEST_AUTH_TOKEN: "1e0975132d3e8502f721ae8d54f84acf"
      TWILIO_TEST_PHONE_NUMBER: "+15005550006"
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/local.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: psycopg2 prerequisites
        run: sudo apt-get install python-dev libpq-dev
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/local.txt
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Test with black
        run: |
          pip install black
          black --check .
      - name: Static typing
        run: |
          mypy .
      - name: NPM Dependencies
        run: |
          yarn install
          yarn run build
      - name: webpack-stats.json
        run: |
          touch webpack-stats.json
          echo '{"status":"done","chunks":{"dashboard":[{"name":"dashboard-5750f43e11ef68c5968d.css","path":"app/static/bundles/dashboard-5750f43e11ef68c5968d.css"},{"name":"dashboard-5750f43e11ef68c5968d.js","path":"app/static/bundles/dashboard-5750f43e11ef68c5968d.js"}],"login":[{"name":"login-5750f43e11ef68c5968d.css","path":"app/static/bundles/login-5750f43e11ef68c5968d.css"},{"name":"login-5750f43e11ef68c5968d.js","path":"app/static/bundles/login-5750f43e11ef68c5968d.js"}],"public":[{"name":"public-5750f43e11ef68c5968d.css","path":"app/static/bundles/public-5750f43e11ef68c5968d.css"},{"name":"public-5750f43e11ef68c5968d.js","path":"app/static/bundles/public-5750f43e11ef68c5968d.js"}]}}' > webpack-stats.json
      - name: Run Tests
        run: |
          coverage run -m pytest --ignore=node_modules
          coverage report --fail-under=100
